# This is a basic workflow to help you get started with Actions

name: Execução de testes

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Ensure script is executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Tests
        run: ./gradlew test

      - name: JaCoCo report
        run: ./gradlew jacocoTestReport

      - name: Check coverage threshold
        run: |
          COVERAGE=$(awk -F'[<>]' '/<td class="ctr[^>]*>[0-9]+%<\/td>/{print substr($3, 1, length($3)-1)}' build/reports/jacoco/test/html/index.html)
          COVERAGE=$(echo "$COVERAGE" | tr -d '%')
          if (( $COVERAGE < 80 )); then
            echo "Erro: Cobertura de código abaixo de 80% (${COVERAGE}%)"
            exit 1
          else
            echo "Cobertura de código: ${COVERAGE}%"
          fi

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/
